apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: govinda52/todobackend:3680d614409b26758a69af366ce2180f6c65bdc4latest
      ports:
        - containerPort: 80
