apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - name: nginx
      image: govinda52/todobackend:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: govinda52/todofrontend:latest
      ports:
        - containerPort: 80
