apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: postgres
spec:
  containers:
    - name: database
      image: postgres:15
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
    - name: backend
      image: govinda52/todobackend:ea726ca716b1e75eaed23041ee1a96ed1f758e0a
      ports:
        - containerPort: 3000
      env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@postgres-service:5432/mydb"

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    - app: frontend
spec:
  containers:
    - name: frontend
      image: govinda52/todofrontend:2866ee1d804be051265727783d3b6b5c1ca8b5e0
      ports:
        - containerPort: 80
